"""Django settings for launcher_app project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]
REFRESH_TOKEN_KEY = os.environ["REFRESH_TOKEN_KEY"].encode()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DEBUG"] != "false"

ALLOWED_HOSTS = ["localhost", "nova.ornl.gov", "nova-test.ornl.gov"]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "https://nova.ornl.gov",
    "https://nova-test.ornl.gov",
]

# Application definition

INSTALLED_APPS = [
    "src.launcher_app.apps.LauncherConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "src.launcher_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "src.launcher_app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# List of emails that can edit the system notification
NOVA_ADMINS = json.loads(os.environ.get("ADMINISTRATOR_EMAILS", "[]"))

# Prefix of tools to retrieve from Galaxy
TOOL_PREFIX = os.environ.get("TOOL_PREFIX", "nova")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication timeout
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", 60 * 60 * 24 * 14))  # 2 weeks

# OAuth settings
BASE_URL = os.environ["BASE_URL"]
OAUTH_PROVIDERS = {}
for provider_id in os.environ["OAUTH_PROVIDERS"].split():
    env_prefix = provider_id.upper()
    OAUTH_PROVIDERS[provider_id] = {
        "name": os.environ.get(f"{env_prefix}_NAME"),
        "auth_url": os.environ.get(f"{env_prefix}_AUTH_URL"),
        "token_url": os.environ.get(f"{env_prefix}_TOKEN_URL"),
        "client_id": os.environ.get(f"{env_prefix}_CLIENT_ID"),
        "client_secret": os.environ.get(f"{env_prefix}_CLIENT_SECRET"),
        "redirect_path": os.environ.get(f"{env_prefix}_REDIRECT_PATH"),
        "scopes": os.environ.get(f"{env_prefix}_SCOPES"),
        "login_url": os.environ.get(f"{env_prefix}_LOGIN_URL"),
    }

# Galaxy settings
GALAXY_URL = os.environ["GALAXY_URL"]
GALAXY_API_KEY_ENDPOINT = os.environ["GALAXY_API_KEY_ENDPOINT"]
GALAXY_HISTORY_NAME = os.environ.get("GALAXY_HISTORY_NAME", "launcher_history")

# System status settings
ALERTS_ENVIRONMENTS = json.loads(os.environ.get("ALERTS_ENVIRONMENTS", "[]"))
ALERTS_FORMAT = os.environ.get("ALERTS_FORMAT", "")
MONITORING_URL = os.environ.get("MONITORING_URL", "")
ALERTS_URL = os.environ.get("ALERTS_URL", "")
TARGETS_URL = os.environ.get("TARGETS_URL", "")

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
