allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true

overrides:
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  lodash@<=4.17.23: '>=4.18.0'
  postcss@<8.5.10: '>=8.5.10'
  js-cookie@<=3.0.5: '>=3.0.7'
  vite@<=6.4.2: '>=6.4.3'
  js-yaml@>=4.0.0 <=4.1.1: '>=4.2.0'
  brace-expansion@>=2.0.0 <2.1.2: '>=2.1.2'
  brace-expansion@<1.1.16: '>=1.1.16'
  js-yaml@>=4.0.0 <4.3.0: '>=4.3.0'
  immutable@>=5.0.0-beta.1 <5.1.8: '>=5.1.8'
  postcss@<=8.5.11: '>=8.5.12'
  postcss@<=8.5.17: '>=8.5.18'
  brace-expansion@<=5.0.7: '>=5.0.8'
  nanoid@<3.3.18: '>=3.3.18'
  toml@<4.2.0: '>=4.2.0'
  toml@<4.1.2: '>=4.1.2'
