# Generated by Django 5.2.11 on 2026-03-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launcher_app', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthSessionState',
        ),
    ]
